=== fliper6/PERFIL_PLC/1º Semestre/PRI/Exercícios_Teste/Notas/project_record.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT project_record (main_title,intro,workteam,abstract,deliverables,date)>

<!-- Título -->
<!ELEMENT main_title (#PCDATA)>

<!-- ***************** 1ª divisão : introdução ***************** -->
<!ELEMENT intro (key_name,title,subtitle?,date_b,date_e,supervisor)>
<!ELEMENT key_name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT date_b (#PCDATA)>
<!ELEMENT date_e (#PCDATA)>
<!ELEMENT supervisor (name,email)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name link CDATA #REQUIRED >
<!ELEMENT email (#PCDATA)>
<!ATTLIST email link CDATA #IMPLIED>

<!-- ****************** 2ª divisão : workteam ****************** -->
<!ELEMENT workteam (member+)>
<!ELEMENT member (name,email)>

<!-- ****************** 3ª divisão : abstract ****************** -->
<!ELEMENT abstract (paragraph)+>
<!ELEMENT paragraph (#PCDATA|italic|bold|underline|link)*>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT underline (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link type (int_link|ext_link) #REQUIRED>

<!-- **************** 4ª divisão : deliverables **************** -->
<!ELEMENT deliverables (ref)*>
<!ELEMENT ref (name)>

<!-- Data -->
<!ELEMENT date (#PCDATA)>

=== fliper6/PERFIL_PLC/1º Semestre/PRI/TPCs/TPC2/project_record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "project_record.dtd">

<project_record>
  <main_title> Project Record </main_title>
  <intro>
    <key_name>PRI2020::TPC2</key_name>
    <title>Ficheiro DTD e respetivo XML</title>
    <!--Optional:-->
    <subtitle> Criação de um ficheiro DTD relativo aos "Project Record" e preeenchimento do XML gerado </subtitle>
    <date_b>19/10/20</date_b>
    <date_e>26/10/20</date_e>
    <supervisor>
      <name link="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</name>
      <email link="mailto:jcr@di.uminho.pt">jcr@di.uminho.pt</email>
    </supervisor>
  </intro>
  <workteam>
    <!--1 or more repetitions:-->
    <member>
      <name link="https://github.com/fliper6/PRI2020">Filipa Santos</name>
      <email link="mailto:a83631@alunos.uminho.pt">a83631@alunos.uminho.pt</email>
    </member>
  </workteam>
  <abstract>
    <!--1 or more repetitions:-->
    <paragraph>
      <!--You have a CHOICE of the next 4 items at this level-->
      A parte "Abstract" do ficheiro XML pode ter vários parágrafos, com texto em <italic>itálico</italic> e texto a <bold>negrito</bold>.
      Também pode conter texto <underline>sublinhado</underline> bem como links <link type="int_link">internos</link> e externos como,
      por exemplo, <link type="ext_link">http://www4.di.uminho.pt/</link>.
    </paragraph>
  </abstract>
  <deliverables>
    <!--Zero or more repetitions:-->
    <ref>
      <name link="https://github.com/fliper6/PRI2020/blob/main/TPC2/project_record.dtd">Ficheiro dtd</name>
    </ref>
  </deliverables>
  <date>string</date>
</project_record>

=== fliper6/PERFIL_PLC/1º Semestre/PRI/Teste2021/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "project_record.dtd">

<project_record>
  <main_title> Project Record </main_title>
  <intro>
    <key_name>PRI2020::Teste</key_name>
    <title>Teste 2020 da UC PRI </title>
    <!--Optional:-->
    <date_b>18/01/21</date_b>
    <supervisor>
      <name link="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</name>
      <email link="mailto:jcr@di.uminho.pt">jcr@di.uminho.pt</email>
    </supervisor>
  </intro>
  <workteam>
    <!--1 or more repetitions:-->
    <member>
      <name link="https://github.com/fliper6/PRI2020">Filipa Santos</name>
      <email link="mailto:a83631@alunos.uminho.pt">a83631@alunos.uminho.pt</email>
    </member>
  </workteam>
  <abstract>
    <!--1 or more repetitions:-->
    <paragraph>
      <!--You have a CHOICE of the next 4 items at this level-->
      Conteúdos relacionados ao teste feito no âmbito da unidade curricular <bold>Processamento e Representação de Informação<bold>, no ano letivo 2020/2021.
    </paragraph>
    <paragraph>
      Relativamente ao <bold>Exercício 1<bold>, foram corrigidos os erros através do "Replace all" ref por "ref" (com o VSCode) e através do script fix_json.js.
    </paragraph>
  </abstract>
  <deliverables>
    <!--Zero or more repetitions:-->
    <ref>
      <name link="https://github.com/fliper6/PRI2020/blob/main/PRI2020-Teste/ex1">Exercício 1</name>
      <name link="https://github.com/fliper6/PRI2020/blob/main/PRI2020-Teste/ex2">Exercício 2</name>
    </ref>
  </deliverables>
  <date>string</date>
</project_record>
